[build]
buildCommand = "cd openmemory/ui && npm install && npm run build"
watchPatterns = ["openmemory/ui/**/*.tsx", "openmemory/ui/**/*.ts", "openmemory/ui/**/*.js", "openmemory/ui/**/*.jsx", "openmemory/ui/**/*.css"]

[deploy]
startCommand = "cd openmemory/ui && npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"