[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Use Docker CMD instead of explicit startCommand
# healthcheckPath = "/health" - Disabled, using Docker healthcheck instead
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
CORTEX_PORT = "8765"
NODE_ENV = "production"