[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python cortex_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "on_failure"

[env]
CORTEX_PORT = "8765"
NODE_ENV = "production"