[variables]
NODE_ENV = "production"
OPENAI_API_KEY = "sk-fake-for-build"
NEXT_PUBLIC_API_URL = "https://cortex-production-58a8.up.railway.app"

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"