[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "npm install -g pnpm && pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://cortex-production.railway.app"