[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3000"
NEXT_PUBLIC_API_URL = "https://cortex-production.railway.app"