[build]
buildCommand = "cd ui && npm install && npm run build"
watchPatterns = ["ui/**/*.tsx", "ui/**/*.ts", "ui/**/*.js", "ui/**/*.jsx", "ui/**/*.css"]

[deploy]
startCommand = "cd ui && npm start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"